import pyautogui
pyautogui.PAUSE=2
pyautogui.press('win')
pyautogui.write('edge')
pyautogui.press('enter')
pyautogui.write("suap")
pyautogui.press('enter')
pyautogui.click(496,292)
pyautogui.click(1805,67)
pyautogui.write("Sei Nome de Usuário:")
pyautogui.press('tab')
pyautogui.write('Sua senha:')
pyautogui.press('tab')
pyautogui.press('tab')
pyautogui.press('enter')